# Generated by Django 4.2.20 on 2025-04-16 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField(default=0)),
                ('matricula', models.CharField(max_length=8)),
                ('kms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, default='', max_length=350)),
                ('tipo', models.ManyToManyField(to='automecom.tiposervico')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('data', models.CharField(default=0, max_length=200)),
                ('hora', models.CharField(default=0, max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('Por confirmar', 'Por confirmar'), ('Confirmado', 'Confirmado'), ('Terminado', 'Terminado')], default='Por confirmar', max_length=50)),
                ('numero', models.IntegerField(default=0)),
                ('orcamento', models.FileField(blank=True, null=True, upload_to='tarefas/')),
                ('observacoes', models.TextField(default='Sem observações', max_length=500)),
                ('fatura', models.FileField(blank=True, null=True, upload_to='tarefas/')),
                ('servicos', models.ManyToManyField(to='automecom.servico')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='automecom.utilizador')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automecom.veiculo')),
            ],
        ),
    ]
