# Generated by Django 4.2.20 on 2025-04-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orcamento',
        ),
    ]
