# Generated by Django 5.1.3 on 2025-03-24 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField(default=0)),
                ('matricula', models.CharField(max_length=8)),
                ('kms', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.ManyToManyField(to='automecom.tiposervico'),
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('data', models.CharField(default=0, max_length=200)),
                ('hora', models.CharField(default=0, max_length=200)),
                ('descricao', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('Por confirmar', 'Por confirmar'), ('Confirmado', 'Confirmado'), ('Terminado', 'Terminado')], default='Por confirmar', max_length=50)),
                ('numero', models.IntegerField(default=0)),
                ('orcamento', models.FileField(blank=True, null=True, upload_to='tarefas/')),
                ('observacoes', models.TextField(default='Sem observações', max_length=500)),
                ('fatura', models.FileField(blank=True, null=True, upload_to='tarefas/')),
                ('servicos', models.ManyToManyField(to='automecom.servico')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='automecom.utilizador')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automecom.veiculo')),
            ],
        ),
    ]
