# Generated by Django 5.1.3 on 2025-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0002_tiposervico_veiculo_servico_descricao_servico_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
