# Generated by Django 4.2.20 on 2025-04-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0003_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.ManyToManyField(blank=True, to='automecom.tiposervico'),
        ),
    ]
