# Generated by Django 5.1.3 on 2025-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0004_alter_servico_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='telefone',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='servicos',
            field=models.ManyToManyField(to='automecom.servico'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.ManyToManyField(to='automecom.tiposervico'),
        ),
    ]
