# Generated by Django 5.1.3 on 2025-04-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0005_remove_orcamento_telefone_orcamento_servicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='veiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automecom.veiculo'),
        ),
    ]
