# Generated by Django 5.1.3 on 2025-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0006_orcamento_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcacao',
            name='telefone',
        ),
        migrations.AddField(
            model_name='marcacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
