# Generated by Django 5.1.3 on 2025-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0007_remove_marcacao_telefone_marcacao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
