# Generated by Django 5.1.3 on 2025-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0009_orcamento_arquivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
