# Generated by Django 5.1.3 on 2025-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0011_alter_servico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='estado_cliente',
            field=models.CharField(choices=[('Pendente do Cliente', 'Pendente do Cliente'), ('Aceita pelo Cliente', 'Aceita pelo Cliente'), ('Recusada pelo Cliente', 'Recusada pelo Cliente')], default='Pendente do Cliente', max_length=50),
        ),
    ]
