# Generated by Django 5.1.3 on 2025-04-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0012_marcacao_estado_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcacao',
            name='estado_cliente',
        ),
    ]
