# Generated by Django 5.1.3 on 2025-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0013_remove_marcacao_estado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='estado',
            field=models.CharField(choices=[('Por confirmar', 'Por confirmar'), ('Confirmado', 'Confirmado'), ('Recusado', 'Recusado')], default='Por confirmar', max_length=50),
        ),
    ]
