# Generated by Django 5.1.3 on 2025-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0014_alter_marcacao_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='estado',
            field=models.CharField(choices=[('Por confirmar', 'Por confirmar'), ('Confirmado', 'Confirmado'), ('Recusado', 'Recusado'), ('Terminada', 'Terminada')], default='Por confirmar', max_length=50),
        ),
    ]
