# Generated by Django 5.1.3 on 2025-05-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0015_alter_marcacao_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='hora',
        ),
    ]
