# Generated by Django 5.1.3 on 2025-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0016_remove_orcamento_data_remove_orcamento_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
