# Generated by Django 5.1.3 on 2025-06-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0017_orcamento_apelido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('data', models.CharField(default=0, max_length=200)),
                ('hora', models.CharField(default=0, max_length=200)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('observacoes', models.TextField(default='Sem observações', max_length=500)),
                ('fatura', models.FileField(blank=True, null=True, upload_to='tarefas/')),
                ('servicos', models.ManyToManyField(to='automecom.servico')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='automecom.utilizador')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automecom.veiculo')),
            ],
        ),
    ]
