# Generated by Django 5.1.3 on 2025-06-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0018_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='kms',
            field=models.IntegerField(),
        ),
    ]
