# Generated by Django 5.1.3 on 2025-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0019_alter_veiculo_kms'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='estado',
            field=models.CharField(choices=[('Em Espera', 'Em Espera de Orçamento'), ('Entregue', 'Orçamento Entregue')], default='Em Espera', max_length=20, verbose_name='Estado do Orçamento'),
        ),
    ]
