# Generated by Django 5.1.3 on 2025-06-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0020_orcamento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='estado',
        ),
    ]
